version: '3'
services:
  event.query:
    build: services/event.query
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - "/code"
  event.create:
    build:
      context: ./services/event.create
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - "/code"
  graphql.gateway:
    build: services/graphql.gateway
    ports:
     - "5000:5000"
    depends_on:
      - event.query
      - mongo
    env_file:
      - .env
    volumes:
      - "/code"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  # rabbit:
  #   container_name: dev_rabbit
  #   hostname: rabbit
  #   image: rabbitmq:3.6.6-management
  #   environment:
  #     - RABBITMQ_DEFAULT_USER = guest
  #     - RABBITMQ_DEFAULT_PASS = guest
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
